// <auto-generated />
using System;
using ASP_First_Poject.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP_First_Poject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP_First_Poject.Models.Camera", b =>
                {
                    b.Property<int>("CameraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FocalLength")
                        .HasColumnType("int");

                    b.Property<int>("Megapixel")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLength")
                        .HasColumnType("int");

                    b.Property<string>("Sensor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CameraID");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("ASP_First_Poject.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeadPhoneID")
                        .HasColumnType("int");

                    b.Property<int?>("LaptopID")
                        .HasColumnType("int");

                    b.Property<string>("MechanicalKeyboardSwitchtype")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PhoneID")
                        .HasColumnType("int");

                    b.Property<int?>("TabletID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentID");

                    b.HasIndex("HeadPhoneID");

                    b.HasIndex("LaptopID");

                    b.HasIndex("MechanicalKeyboardSwitchtype");

                    b.HasIndex("PhoneID");

                    b.HasIndex("TabletID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ASP_First_Poject.Models.HeadPhone", b =>
                {
                    b.Property<int>("HeadPhoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Battery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Bluetooth")
                        .HasColumnType("real");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectingGate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedRGB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Speaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<DateTime>("YearManufact")
                        .HasColumnType("datetime2");

                    b.HasKey("HeadPhoneID");

                    b.ToTable("HeadPhones");
                });

            modelBuilder.Entity("ASP_First_Poject.Models.Laptop", b =>
                {
                    b.Property<int>("LaptopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Battery")
                        .HasColumnType("float");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CameraID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fingersensor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Ram")
                        .HasColumnType("int");

                    b.Property<int>("ScreenSize")
                        .HasColumnType("int");

                    b.Property<string>("Speaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.Property<string>("Touchpad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<DateTime>("YearManufact")
                        .HasColumnType("datetime2");

                    b.HasKey("LaptopID");

                    b.HasIndex("CameraID");

                    b.ToTable("Laptops");
                });

            modelBuilder.Entity("ASP_First_Poject.Models.MechanicalKeyboard", b =>
                {
                    b.Property<string>("Switchtype")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Battery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Bluetooth")
                        .HasColumnType("real");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectingGate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keycap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedRGB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SwitchBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<DateTime>("YearManufact")
                        .HasColumnType("datetime2");

                    b.HasKey("Switchtype");

                    b.ToTable("MechanicalKeyboards");
                });

            modelBuilder.Entity("ASP_First_Poject.Models.Phone", b =>
                {
                    b.Property<int>("PhoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Battery")
                        .HasColumnType("float");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MainCameraCameraID")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Ram")
                        .HasColumnType("int");

                    b.Property<int>("ScreenSize")
                        .HasColumnType("int");

                    b.Property<int?>("SelfieCameraCameraID")
                        .HasColumnType("int");

                    b.Property<string>("Speaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<DateTime>("YearManufact")
                        .HasColumnType("datetime2");

                    b.HasKey("PhoneID");

                    b.HasIndex("MainCameraCameraID");

                    b.HasIndex("SelfieCameraCameraID");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("ASP_First_Poject.Models.Tablet", b =>
                {
                    b.Property<int>("TabletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Battery")
                        .HasColumnType("float");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MainCameraCameraID")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Ram")
                        .HasColumnType("int");

                    b.Property<int>("ScreenSize")
                        .HasColumnType("int");

                    b.Property<int?>("SelfieCameraCameraID")
                        .HasColumnType("int");

                    b.Property<string>("Speaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<DateTime>("YearManufact")
                        .HasColumnType("datetime2");

                    b.HasKey("TabletID");

                    b.HasIndex("MainCameraCameraID");

                    b.HasIndex("SelfieCameraCameraID");

                    b.ToTable("Tablets");
                });

            modelBuilder.Entity("ASP_First_Poject.Models.Comment", b =>
                {
                    b.HasOne("ASP_First_Poject.Models.HeadPhone", null)
                        .WithMany("Comments")
                        .HasForeignKey("HeadPhoneID");

                    b.HasOne("ASP_First_Poject.Models.Laptop", null)
                        .WithMany("Comments")
                        .HasForeignKey("LaptopID");

                    b.HasOne("ASP_First_Poject.Models.MechanicalKeyboard", null)
                        .WithMany("Comments")
                        .HasForeignKey("MechanicalKeyboardSwitchtype");

                    b.HasOne("ASP_First_Poject.Models.Phone", null)
                        .WithMany("Comments")
                        .HasForeignKey("PhoneID");

                    b.HasOne("ASP_First_Poject.Models.Tablet", null)
                        .WithMany("Comments")
                        .HasForeignKey("TabletID");
                });

            modelBuilder.Entity("ASP_First_Poject.Models.Laptop", b =>
                {
                    b.HasOne("ASP_First_Poject.Models.Camera", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraID");
                });

            modelBuilder.Entity("ASP_First_Poject.Models.Phone", b =>
                {
                    b.HasOne("ASP_First_Poject.Models.Camera", "MainCamera")
                        .WithMany()
                        .HasForeignKey("MainCameraCameraID");

                    b.HasOne("ASP_First_Poject.Models.Camera", "SelfieCamera")
                        .WithMany()
                        .HasForeignKey("SelfieCameraCameraID");
                });

            modelBuilder.Entity("ASP_First_Poject.Models.Tablet", b =>
                {
                    b.HasOne("ASP_First_Poject.Models.Camera", "MainCamera")
                        .WithMany()
                        .HasForeignKey("MainCameraCameraID");

                    b.HasOne("ASP_First_Poject.Models.Camera", "SelfieCamera")
                        .WithMany()
                        .HasForeignKey("SelfieCameraCameraID");
                });
#pragma warning restore 612, 618
        }
    }
}
